#!/usr/bin/env bash
# configures an Nginx server to have a custom 404 page that contains the string 'Ceci n'est pas une page'

apt-get -y update
apt-get -y install nginx

echo 'Holberton School' > /var/www/html/index.nginx-debian.html

# Performing a "moved permanently redirection" (301)
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/https://www.youtube.com/watch?v=QH2-TGUlwu4\/besthor permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default


echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
